<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ChildCateogry extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        


        $child_cat=[
            ['id'=>'81','name_en'=>'Beauty Tools & Devices','name_ar'=>'','slug'=>'Beauty-Tools-Devices','status'=>'0','subcategory_id'=>'61'],
            ['id'=>'82','name_en'=>'Cleansers & Exfoliators','name_ar'=>'','slug'=>'Cleansers-Exfoliators','status'=>'0','subcategory_id'=>'61'],
            ['id'=>'153','name_en'=>'Deodorants','name_ar'=>'','slug'=>'Deodorants','status'=>'0','subcategory_id'=>'61'],
            ['id'=>'63','name_en'=>'Eye Care','name_ar'=>'','slug'=>'Eye-Care','status'=>'0','subcategory_id'=>'61'],
            ['id'=>'83','name_en'=>'Kit sets','name_ar'=>'','slug'=>'Kit-sets','status'=>'0','subcategory_id'=>'61'],
            ['id'=>'80','name_en'=>'Lip Care','name_ar'=>'','slug'=>'Lip-Care','status'=>'0','subcategory_id'=>'61'],
            ['id'=>'118','name_en'=>'Moisturizers','name_ar'=>'','slug'=>'Moisturizers','status'=>'0','subcategory_id'=>'61'],
            ['id'=>'79','name_en'=>'Sun protection','name_ar'=>'','slug'=>'Sun-protection','status'=>'0','subcategory_id'=>'61'],
            ['id'=>'65','name_en'=>'Treatments & Serums','name_ar'=>'','slug'=>'Treatments-Serums','status'=>'0','subcategory_id'=>'61'],
            ['id'=>'92','name_en'=>'Baby & Mom','name_ar'=>'','slug'=>'Baby & Mom','status'=>'0','subcategory_id'=>'84'],
            ['id'=>'85','name_en'=>'Bath & Shower','name_ar'=>'','slug'=>'Bath-Shower','status'=>'0','subcategory_id'=>'84'],
            ['id'=>'90','name_en'=>'Body & Feet','name_ar'=>'','slug'=>'Body-Feet','status'=>'0','subcategory_id'=>'84'],
            ['id'=>'86','name_en'=>'Body Scrubs & Exfoliators','name_ar'=>'','slug'=>'Body-Scrubs-Exfoliators','status'=>'0','subcategory_id'=>'84'],
            ['id'=>'88','name_en'=>'Body Treatments','name_ar'=>'','slug'=>'Body-Treatments','status'=>'0','subcategory_id'=>'84'],
            ['id'=>'89','name_en'=>'Lotions & Oils','name_ar'=>'','slug'=>'Lotions-Oils','status'=>'0','subcategory_id'=>'84'],
            ['id'=>'438','name_en'=>'Perfume','name_ar'=>'','slug'=>'Perfume','status'=>'0','subcategory_id'=>'84'],
            ['id'=>'91','name_en'=>'Supplements & Wellness','name_ar'=>'','slug'=>'Supplements-Wellness','status'=>'0','subcategory_id'=>'84'],
            ['id'=>'439','name_en'=>'Women Perfume','name_ar'=>'','slug'=>'Women-Perfume','status'=>'0','subcategory_id'=>'84'],
            ['id'=>'97','name_en'=>'Conditioner','name_ar'=>'','slug'=>'Conditioner','status'=>'0','subcategory_id'=>'93'],
            ['id'=>'96','name_en'=>'Dry Shampoo','name_ar'=>'','slug'=>'Dry-Shampoo','status'=>'0','subcategory_id'=>'93'],
            ['id'=>'99','name_en'=>'Hair Mask','name_ar'=>'','slug'=>'Hair-Mask','status'=>'0','subcategory_id'=>'93'],
            ['id'=>'110','name_en'=>'Hair Removal','name_ar'=>'','slug'=>'Hair-Removal','status'=>'0','subcategory_id'=>'93'],
            ['id'=>'98','name_en'=>'Hair Treatments','name_ar'=>'','slug'=>'Hair-Treatments','status'=>'0','subcategory_id'=>'93'],
            ['id'=>'113','name_en'=>'More','name_ar'=>'','slug'=>'More','status'=>'0','subcategory_id'=>'93'],
            ['id'=>'102','name_en'=>'Natural Hair Care','name_ar'=>'','slug'=>'Natural-Hair-Care','status'=>'0','subcategory_id'=>'93'],
            ['id'=>'94','name_en'=>'Shampoo','name_ar'=>'','slug'=>'Shampoo','status'=>'0','subcategory_id'=>'93'],
            ['id'=>'103','name_en'=>'Shop By Hair Type','name_ar'=>'','slug'=>'Shop-Hair-Type','status'=>'0','subcategory_id'=>'93'],
            ['id'=>'100','name_en'=>'Styling Products','name_ar'=>'','slug'=>'Styling-Products','status'=>'0','subcategory_id'=>'93'],
            ['id'=>'101','name_en'=>'Tools & Brushes','name_ar'=>'','slug'=>'Tools-Brushes','status'=>'0','subcategory_id'=>'93'],
            ['id'=>'149','name_en'=>'Accessories','name_ar'=>'','slug'=>'Accessories','status'=>'0','subcategory_id'=>'147'],
            ['id'=>'150','name_en'=>'Dental Floss & Picks','name_ar'=>'','slug'=>'Dental-Floss-Picks','status'=>'0','subcategory_id'=>'147'],
            ['id'=>'152','name_en'=>'Mouth Wash','name_ar'=>'','slug'=>'Mouth Wash','status'=>'0','subcategory_id'=>'147'],
            ['id'=>'148','name_en'=>'Toothbrushes','name_ar'=>'','slug'=>'Toothbrushes','status'=>'0','subcategory_id'=>'147'],
            ['id'=>'151','name_en'=>'Toothpaste','name_ar'=>'','slug'=>'Toothpaste','status'=>'0','subcategory_id'=>'147'],
            ['id'=>'187','name_en'=>'Brands','name_ar'=>'','slug'=>'Brands','status'=>'0','subcategory_id'=>'159'],
            ['id'=>'173','name_en'=>'Eyes Makeup','name_ar'=>'','slug'=>'Eyes-Makeup','status'=>'0','subcategory_id'=>'159'],
            ['id'=>'160','name_en'=>'Face','name_ar'=>'','slug'=>'Face','status'=>'0','subcategory_id'=>'159'],
            ['id'=>'168','name_en'=>'Lips','name_ar'=>'','slug'=>'Lips','status'=>'0','subcategory_id'=>'159'],
            ['id'=>'186','name_en'=>'Makeup Remover','name_ar'=>'','slug'=>'Makeup-Remover','status'=>'0','subcategory_id'=>'159'],
            ['id'=>'180','name_en'=>'More','name_ar'=>'','slug'=>'More','status'=>'0','subcategory_id'=>'159'],
            ['id'=>'185','name_en'=>'Tools & Brushes','name_ar'=>'','slug'=>'Tools-Brushes','status'=>'0','subcategory_id'=>'159'],
            ['id'=>'426','name_en'=>'Polish','name_ar'=>'','slug'=>'Polish','status'=>'0','subcategory_id'=>'184'],
            ['id'=>'427','name_en'=>'Polish Remover','name_ar'=>'','slug'=>'Polish-Remover','status'=>'0','subcategory_id'=>'184'],
            ['id'=>'428','name_en'=>'Treatments','name_ar'=>'','slug'=>'Treatments','status'=>'0','subcategory_id'=>'184'],
            ['id'=>'195','name_en'=>'Body Care','name_ar'=>'','slug'=>'Body-Care','status'=>'0','subcategory_id'=>'190'],
            ['id'=>'193','name_en'=>'Cleansers & Exfoliators','name_ar'=>'','slug'=>'Cleansers-Exfoliators','status'=>'0','subcategory_id'=>'190'],
            ['id'=>'194','name_en'=>'Hair Products','name_ar'=>'','slug'=>'Hair-Products','status'=>'0','subcategory_id'=>'190'],
            ['id'=>'192','name_en'=>'Moisturizers & Treatments','name_ar'=>'','slug'=>'Moisturizers-Treatments','status'=>'0','subcategory_id'=>'190'],
            ['id'=>'191','name_en'=>'Shaving & Grooming','name_ar'=>'','slug'=>'Shaving-Grooming','status'=>'0','subcategory_id'=>'190'],
            ['id'=>'196','name_en'=>'Shop By Concers','name_ar'=>'','slug'=>'Shop-By-Concers','status'=>'0','subcategory_id'=>'190'],
            ['id'=>'205','name_en'=>'Best Sellers','name_ar'=>'','slug'=>'Best-Sellers','status'=>'0','subcategory_id'=>'203'],
            ['id'=>'206','name_en'=>'Kits & Sets','name_ar'=>'','slug'=>'Kits-Sets','status'=>'0','subcategory_id'=>'203'],
            ['id'=>'204','name_en'=>'New Arrivals','name_ar'=>'','slug'=>'New-Arrivals','status'=>'0','subcategory_id'=>'203'],
            ['id'=>'223','name_en'=>'Cell Phone Accessories','name_ar'=>'','slug'=>'Cell-Phone-Accessories','status'=>'0','subcategory_id'=>'207'],
            ['id'=>'221','name_en'=>'Cell Phones & Smartphones','name_ar'=>'','slug'=>'Cell-Phones-Smartphones','status'=>'0','subcategory_id'=>'207'],
            ['id'=>'225','name_en'=>'Cell Phones & Smartphones Parts','name_ar'=>'','slug'=>'Cell-Phones-Smartphones-Parts','status'=>'0','subcategory_id'=>'207'],
            ['id'=>'226','name_en'=>'Shop By Brands','name_ar'=>'','slug'=>'Shop-By-Brands','status'=>'0','subcategory_id'=>'207'],
            ['id'=>'224','name_en'=>'Smart Watch Accessories','name_ar'=>'','slug'=>'Smart-Watch-Accessories','status'=>'0','subcategory_id'=>'207'],
            ['id'=>'222','name_en'=>'Smart Watches','name_ar'=>'','slug'=>'Smart-Watches','status'=>'0','subcategory_id'=>'207'],
            ['id'=>'230','name_en'=>'Computer Components & Parts','name_ar'=>'','slug'=>'Computer-Components-Parts','status'=>'0','subcategory_id'=>'208'],
            ['id'=>'237','name_en'=>'Desktops & All-In-Ones','name_ar'=>'','slug'=>'Desktops-All-In-Ones','status'=>'0','subcategory_id'=>'208'],
            ['id'=>'232','name_en'=>'Drives, Storage & Blank Media','name_ar'=>'','slug'=>'Drives-Storage-Blank-Media','status'=>'0','subcategory_id'=>'208'],
            ['id'=>'234','name_en'=>'eBook Readers','name_ar'=>'','slug'=>'eBook-Readers','status'=>'0','subcategory_id'=>'208'],
            ['id'=>'236','name_en'=>'Enterprise Networking, Servers','name_ar'=>'','slug'=>'Enterprise-Networking-Servers','status'=>'0','subcategory_id'=>'208'],
            ['id'=>'240','name_en'=>'Home Networking & Connectivity','name_ar'=>'','slug'=>'Home-Networking-Connectivity','status'=>'0','subcategory_id'=>'208'],
            ['id'=>'238','name_en'=>'Keyboards, Mice & Pointers','name_ar'=>'','slug'=>'Keyboards-Mice-Pointers','status'=>'0','subcategory_id'=>'208'],
            ['id'=>'231','name_en'=>'Laptops & Desktop Accessories','name_ar'=>'','slug'=>'Laptops-Desktop-Accessories','status'=>'0','subcategory_id'=>'208'],
            ['id'=>'229','name_en'=>'Laptops & Netbooks & Tablets','name_ar'=>'','slug'=>'Laptops-Netbooks-Tablets','status'=>'0','subcategory_id'=>'208'],
            ['id'=>'437','name_en'=>'monitor cameras','name_ar'=>'','slug'=>'monitor-cameras','status'=>'0','subcategory_id'=>'208'],
            ['id'=>'233','name_en'=>'Printers, Scanners & Supplies','name_ar'=>'','slug'=>'Printers-Scanners-Supplies','status'=>'0','subcategory_id'=>'208'],
            ['id'=>'239','name_en'=>'Softwares','name_ar'=>'','slug'=>'Softwares','status'=>'0','subcategory_id'=>'208'],
            ['id'=>'248','name_en'=>'Controllers & Attachments','name_ar'=>'','slug'=>'Controllers-Attachments','status'=>'0','subcategory_id'=>'209'],
            ['id'=>'242','name_en'=>'Game Consoles Accessories','name_ar'=>'','slug'=>'Game-Consoles-Accessories','status'=>'0','subcategory_id'=>'209'],
            ['id'=>'243','name_en'=>'Games','name_ar'=>'','slug'=>'Games','status'=>'0','subcategory_id'=>'209'],
            ['id'=>'241','name_en'=>'Games Consoles','name_ar'=>'','slug'=>'Games-Consoles','status'=>'0','subcategory_id'=>'209'],
            ['id'=>'249','name_en'=>'Prepaid Gaming Cards','name_ar'=>'','slug'=>'Prepaid-Gaming-Cards','status'=>'0','subcategory_id'=>'209'],
            ['id'=>'250','name_en'=>'Toys to Life','name_ar'=>'','slug'=>'Toys-to-Life','status'=>'0','subcategory_id'=>'209'],
            ['id'=>'219','name_en'=>'New Brands','name_ar'=>'','slug'=>'New-Brands','status'=>'0','subcategory_id'=>'218'],
            ['id'=>'220','name_en'=>'Popular Brands','name_ar'=>'','slug'=>'Popular-Brands','status'=>'0','subcategory_id'=>'218'],
            ['id'=>'257','name_en'=>'Kids & Baby','name_ar'=>'','slug'=>'Kids-Baby','status'=>'0','subcategory_id'=>'251'],
            ['id'=>'255','name_en'=>'Men','name_ar'=>'','slug'=>'Men','status'=>'0','subcategory_id'=>'251'],
            ['id'=>'256','name_en'=>'Women','name_ar'=>'','slug'=>'Women','status'=>'0','subcategory_id'=>'251'],
            ['id'=>'344','name_en'=>'Kids & Baby','name_ar'=>'','slug'=>'Kids-Baby','status'=>'0','subcategory_id'=>'252'],
            ['id'=>'342','name_en'=>'Men','name_ar'=>'','slug'=>'Men','status'=>'0','subcategory_id'=>'252'],
            ['id'=>'346','name_en'=>'Shoe Care','name_ar'=>'','slug'=>'Shoe-Care','status'=>'0','subcategory_id'=>'252'],
            ['id'=>'343','name_en'=>'Women','name_ar'=>'','slug'=>'Women','status'=>'0','subcategory_id'=>'252'],
            ['id'=>'387','name_en'=>'Anklets','name_ar'=>'','slug'=>'Anklets','status'=>'0','subcategory_id'=>'253'],
            ['id'=>'388','name_en'=>'Bracelets','name_ar'=>'','slug'=>'Bracelets','status'=>'0','subcategory_id'=>'253'],
            ['id'=>'389','name_en'=>'Earrings','name_ar'=>'','slug'=>'Earrings','status'=>'0','subcategory_id'=>'253'],
            ['id'=>'392','name_en'=>'Men','name_ar'=>'','slug'=>'Men','status'=>'0','subcategory_id'=>'253'],
            ['id'=>'390','name_en'=>'Necklaces','name_ar'=>'','slug'=>'Necklaces','status'=>'0','subcategory_id'=>'253'],
            ['id'=>'391','name_en'=>'Rings','name_ar'=>'','slug'=>'Rings','status'=>'0','subcategory_id'=>'253'],
            ['id'=>'395','name_en'=>'Sets','name_ar'=>'','slug'=>'Sets','status'=>'0','subcategory_id'=>'253'],
            ['id'=>'401','name_en'=>'Belts','name_ar'=>'','slug'=>'Belts','status'=>'0','subcategory_id'=>'254'],
            ['id'=>'406','name_en'=>'Cufflinks & Sewing','name_ar'=>'','slug'=>'Cufflinks-Sewing','status'=>'0','subcategory_id'=>'254'],
            ['id'=>'405','name_en'=>'Electronic Accessories','name_ar'=>'','slug'=>'Electronic-Accessories','status'=>'0','subcategory_id'=>'254'],
            ['id'=>'399','name_en'=>'Headwear','name_ar'=>'','slug'=>'Headwear','status'=>'0','subcategory_id'=>'254'],
            ['id'=>'397','name_en'=>'Homeware','name_ar'=>'','slug'=>'Homeware','status'=>'0','subcategory_id'=>'254'],
            ['id'=>'407','name_en'=>'Keyrings','name_ar'=>'','slug'=>'Keyrings','status'=>'0','subcategory_id'=>'254'],
            ['id'=>'402','name_en'=>'Multipaks','name_ar'=>'','slug'=>'Multipaks','status'=>'0','subcategory_id'=>'254'],
            ['id'=>'408','name_en'=>'Purses & Wallets','name_ar'=>'','slug'=>'Purses-Wallets','status'=>'0','subcategory_id'=>'254'],
            ['id'=>'400','name_en'=>'Scarves','name_ar'=>'','slug'=>'Scarves','status'=>'0','subcategory_id'=>'254'],
            ['id'=>'404','name_en'=>'Sports Accessories','name_ar'=>'','slug'=>'Sports-Accessories','status'=>'0','subcategory_id'=>'254'],
            ['id'=>'393','name_en'=>'Sunglasses','name_ar'=>'','slug'=>'Sunglasses','status'=>'0','subcategory_id'=>'254'],
            ['id'=>'403','name_en'=>'Travel Accessories','name_ar'=>'','slug'=>'Travel-Accessories','status'=>'0','subcategory_id'=>'254'],
            ['id'=>'396','name_en'=>'Watches','name_ar'=>'','slug'=>'Watches','status'=>'0','subcategory_id'=>'254'],
            ['id'=>'413','name_en'=>'Bedroom','name_ar'=>'','slug'=>'Bedroom','status'=>'0','subcategory_id'=>'410'],
            ['id'=>'418','name_en'=>'Home Fragrance','name_ar'=>'','slug'=>'Home-Fragrance','status'=>'0','subcategory_id'=>'410'],
            ['id'=>'414','name_en'=>'Kitchen','name_ar'=>'','slug'=>'Kitchen','status'=>'0','subcategory_id'=>'410'],
            ['id'=>'415','name_en'=>'Living Room','name_ar'=>'','slug'=>'Living-Room','status'=>'0','subcategory_id'=>'410'],
            ['id'=>'416','name_en'=>'Outdoor','name_ar'=>'','slug'=>'Outdoor','status'=>'0','subcategory_id'=>'410'],
            ['id'=>'412','name_en'=>'toilet','name_ar'=>'','slug'=>'toilet','status'=>'0','subcategory_id'=>'410'],
            ['id'=>'422','name_en'=>'Fragrance','name_ar'=>'','slug'=>'Fragrance','status'=>'0','subcategory_id'=>'411'],
            ['id'=>'423','name_en'=>'Gifts Sets','name_ar'=>'','slug'=>'Gifts-Sets','status'=>'0','subcategory_id'=>'411'],
            ['id'=>'421','name_en'=>'Jewellery','name_ar'=>'','slug'=>'Jewellery','status'=>'0','subcategory_id'=>'411'],
            ['id'=>'424','name_en'=>'Leather Goods','name_ar'=>'','slug'=>'Leather-Goods','status'=>'0','subcategory_id'=>'411'],
            ['id'=>'425','name_en'=>'Watches','name_ar'=>'','slug'=>'Watches','status'=>'0','subcategory_id'=>'411'],
            ['id'=>'430','name_en'=>'Lenses','name_ar'=>'','slug'=>'Lenses','status'=>'0','subcategory_id'=>'429'],
            ['id'=>'431','name_en'=>'lenses tools','name_ar'=>'','slug'=>'lenses-tools','status'=>'0','subcategory_id'=>'429'],
        ];

        DB::table('childcategories')->insert($child_cat);
    }
}
